### PR TITLE
Set executable permissions to files with Executable flag

### LINKED ISSUE #155: Executable bits not properly set
Downloading a depot which has executables in it (e.g. a dedicated server), on Linux, doesn't set the bits necessary to make the files executable.

### PR DESCRIPTION
**Pull request by js6pak**
Closes #155

### CODE REVIEW

**Review by yaakov-h — COMMENTED** [review]
I'm always a little hesitant taking new dependencies

@azuisleet are you OK with the new dependency on Mono.Posix or should we P/Invoke the underlying function directly?

Also, is this the only place where we need to do the check? At a glanc, it looks to me like the following sequence would fail:

1. Download build v1 w/o executable bit
2. Developer uploads build v2 that sets executable bit on existing file
3. We update to build v2
4. File might not be marked as +x

**Comment by js6pak** [comment]
I could just move the whole chmod block to [here](https://github.com/SteamRE/DepotDownloader/blob/33483e594b5c6a640ec0339e7694e5dbfa1e6a92/DepotDownloader/ContentDownloader.cs#L1193), then executable flag would be always set. Question is isn't it better to respect eventual removal of the flag by the user and check it only when new build sets it explicitly, but then, can you get the old build info easily (assuming you are upgrading a build downloaded by steamcmd which doesn't have .DepotDownloader etc)?
With P/Invoke keep in mind we'd also have to get existing file permissions, parse them, add exe flag and them set them manually

**Comment by yaakov-h** [comment]
Removal reminds me that we should probably unset the executable flag if the old file had it but the new depot does not specify it.

I think it's an interesting choice to have - do we respect the wishes of the user by preserving manual modifications to the downloaded file data/metadata, or do we respect the wishes of the user by updating the existing content to match the new depot/build definition?

**Comment by js6pak** [comment]
Played around with steamcmd for a bit, seems like it sets exe permission only when the file is actually updated either by new build or `validate` and changed hash
Changed this PR to add/remove execute permissions when file is created/invalid and only if previous manifest doesn't exist or executable flag changed in the new manifest

**Comment by azuisleet** [comment]
In this case, I would prefer we P/Invoke to chmod the files. Looking at the artifacts, Mono.Posix pulls in a bunch of runtime helpers that I would prefer not to have to distribute.

**Comment by azuisleet** [comment]
This looks good. I merged the new .editorconfig, can you reformat this PR to match?

**Comment by azuisleet** [comment]
On my Ubuntu install, `stat` is actually a wrapper for `__xstat`

```
nm -D /usr/lib/x86_64-linux-gnu/libc.so.6 | grep __xstat
```

Can you confirm your environment?

**Comment by js6pak** [comment]
Same here but seems to be glibc specific, why does it matter anyway?

**Comment by azuisleet** [comment]
There isn't an actual export for `stat` in libc in my environment.

**Comment by js6pak** [comment]
> https://stackoverflow.com/questions/67395291/stat-method-not-found-in-libc-so-6

Well, now I know why Mono.Posix had a native helper for `stat`

**Comment by azuisleet** [comment]
I likely have a couple adjustments to this, but I think this is ready. I'll change it to `__xstat` for now for the Linux path.

**Comment by js6pak** [comment]
Btw `__xstat` works on my system (although you need to add the int `ver` that depends on the system arch). Are you able to check it with macos?

**Comment by azuisleet** [comment]
ABI support is a bit of a mess, but it's functional. Check out the last commit 815ac10849a29b2ae265717683036ad1b60cc1a1 and if we agree, this should be ready.

**Pull request merged**
