### PR TITLE
Print progress log after each chunk

### PR DESCRIPTION
**Pull request by xPaw**
For big files there is no progress until the file fully downloads

### CODE REVIEW

**Comment by azuisleet** [comment]
Is this going to be too noisy? Especially for users who don't use it interactively?

**Comment by psychonic** [comment]
I vaguely recall DepotDownloader having that kind of output long ago, and it being extremely noisy when piping the output to a file.

**Comment by yaakov-h** [comment]
Do we need to throw it behind a verbosity flag then?

**Comment by xPaw** [comment]
See #95

**Pull request closed without merging**
